# Generated by Django 5.1.7 on 2025-06-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="logo",
            field=models.ImageField(upload_to="team_logos/"),
        ),
    ]
