# Generated by Django 5.1.7 on 2025-06-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_alter_team_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="league",
        ),
        migrations.DeleteModel(
            name="League",
        ),
    ]
