# Generated by Django 5.1.7 on 2025-07-08 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_is_draft_alter_report_unique_together'),
        ('teams', '0005_remove_team_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('team', 'author', 'is_draft')},
        ),
    ]
