# Generated by Django 5.1.7 on 2025-05-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="firstName",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="lastName",
            new_name="last_name",
        ),
    ]
