# Generated by Django 5.1.7 on 2025-06-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_rename_firstname_user_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="default_user", max_length=150, unique=True),
        ),
    ]
