# Generated by Django 5.1.7 on 2025-06-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="default_user", max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
